### ISSUE TITLE
Improve header beneath article for author area

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#30]
See https://github.com/davisshaver/terminal/issues/7

> These headers at the bottom of the article don't look like they are headers, especially since they are smaller and lighter than the body text

**Comment by pixelyunicorn** [comment]
This is not an issue with Onward State, looks like this issue is can mostly be solved by setting the "Loop header background color" and "Loop Header Text Color" in the customiser different from the main background color

![image](https://user-images.githubusercontent.com/607807/45597761-d12a9400-b99e-11e8-855a-dd9072d3fc5c.png)

One possible color pallete is a white text on a black/gray background - 

![image](https://user-images.githubusercontent.com/607807/45597836-b1e03680-b99f-11e8-8748-5ffc41d8f010.png)

**Comment by davisshaver** [comment]
@pixelyunicorn this looks better with the customizer changes, think we can close?
