### ISSUE TITLE
Spend an hour identifying design rough spots with OnwardState.com

### ISSUE THREAD

**Issue by davisshaver** [davisshaver/terminal#6]

**Comment by pixelyunicorn** [comment]
Since you asked for it, here's an hour of me going thru the site and more or less roasting it designwise -

# Overall

The first thing that stands out is that there is only a single headline is visible before the fold on a desktop.

![image](https://user-images.githubusercontent.com/607807/45061865-4f6c6980-b074-11e8-9e5e-8983d9b8e827.png)

Compare that to The Verge (https://www.theverge.com/) or Temple News (https://temple-news.com/), where multiple headlines are visible before the fold even with ads.

![image](https://user-images.githubusercontent.com/607807/45061946-aeca7980-b074-11e8-8b49-bd45a099202c.png)

![image](https://user-images.githubusercontent.com/607807/45061952-bab63b80-b074-11e8-86fd-9c1d4b7a003a.png)

The choice of fonts and/or use of typography isn't that great. There's no clear distinction of which font should be used where, _especially_ when it comes to headers.
 
![image](https://user-images.githubusercontent.com/607807/45062186-d40bb780-b075-11e8-95dd-7b074e0f3e3d.png)

The card layout in general also seems dated

# Header

Contrast with the `follow us!` link in the header

![image](https://user-images.githubusercontent.com/607807/45061210-81300100-b071-11e8-8379-25172788a250.png)

Tiny detail, but the header would look nicer if the bear was flush or covered by the navbar below it. Right now, the bear looks suddenly cut off and floating in mid-air.

![image](https://user-images.githubusercontent.com/607807/45062008-02d55e00-b075-11e8-94d2-5372bcd8ed93.png)

# Nav Menu

The actual nav bar doesn't seem to be taking up the full width (right side)

![image](https://user-images.githubusercontent.com/607807/45061306-f4397780-b071-11e8-9817-f714200c418c.png)

There is inconsistent line height between the 2 sections. Is tips part of the About section or its own item?

![image](https://user-images.githubusercontent.com/607807/45061444-8b9eca80-b072-11e8-82e8-258378dc8fa8.png)

It is very difficult to distinguish between the border of each link. Some may read it as 110k twitter, 31.3k snapchat

![image](https://user-images.githubusercontent.com/607807/45061382-3f538a80-b072-11e8-93e0-e3a3d67b73cb.png)

There are 2 symbols at the bottom of the nav that do not have a clear meaning. The average college student won't understand that the top icon means RSS (or what it even is). The icon at the bottom is very hard to see and gives no clue to what is actually is.

![image](https://user-images.githubusercontent.com/607807/45061484-b38e2e00-b072-11e8-93cc-3caf81e4142c.png)

# Search

It isn't clear how instant search actually works, at first glance it seems broken and not very instant. It is only when focus is lost from the text box when search happens. (Ideally, this should happen on every character change).

The reset button doesn't look like a button. It also doesn't make sense to have the 3 options appear as full rows since the input content doesn't take much space at all, so put them as 3 columns instead.

![image](https://user-images.githubusercontent.com/607807/45061657-6e1e3080-b073-11e8-9796-a75a7aa943a2.png)

It is also unclear if this specific heading block is part of the page or the search box

![image](https://user-images.githubusercontent.com/607807/45062125-88590e00-b075-11e8-8837-5dc29020d6a5.png)

Example searches should be clickable, or better yet show up when the input is focused (styled like Google autocomplete) 

![image](https://user-images.githubusercontent.com/607807/45061713-b50c2600-b073-11e8-9c8f-d3a591fe85a9.png)

Entering a search term, letting the instant search happen, then clearing the search box does not actually reset the page to its original content.

It also isn't clear how to close the search box.

# Sidebar

Text indentations do not make sense, and it's difficult to visually distinguish between the sidebar header and the rest of the options. A little bold on the title wouldn't hurt.

![image](https://user-images.githubusercontent.com/607807/45061236-986eee80-b071-11e8-88be-3a14afbc95b6.png)

Bold font on sidebar item hover isn't actually bold, but a terrible browser render. The use of bold font doesn't make sense in this case either, a background color change or text underline is more appropriate.

![image](https://user-images.githubusercontent.com/607807/45061831-18965380-b074-11e8-9ca7-e2908f78fccc.png)

# Homepage

This card-in-card newsletter signup looks inconsistent with the rest of the site

![image](https://user-images.githubusercontent.com/607807/45062155-b1799e80-b075-11e8-9bd5-e5badcbbd3be.png)

This particular section lacks a header or clues of what purpose it serves. With trackpad as a mouse devices, it is impossible to know that this section is actually scrollable. Also, a headline is cut off

![image](https://user-images.githubusercontent.com/607807/45062249-1503cc00-b076-11e8-834a-2f9a321061e0.png)

These arrows are very difficult to see and blend in with the images. 

![image](https://user-images.githubusercontent.com/607807/45062277-2fd64080-b076-11e8-99c3-0399eef0b11a.png)

Trending is alright, typography is actually used well. One thing I'd improve is the dropdown.

![image](https://user-images.githubusercontent.com/607807/45062324-601ddf00-b076-11e8-81b8-2d6b3ec95fc1.png)

Why is the author suddenly shown here but not at the headlines at the top of the page? The length of the author tag should be fixed so that it doesn't overflow.

The date format could be better (use time-relative terms like `43 minutes ago`if very recent, `Today at 4:11 pm` if same day,  `September 2` if previous days since the reader won't care about time). Perhaps show these 2 items on on seperate lines?

![image](https://user-images.githubusercontent.com/607807/45062375-96f3f500-b076-11e8-9b27-545f6bc10af4.png)

Why does a `Football` header appear on top of this article but not the rest? Especially since many of the other posts are football related? Is this the latest article with the Football tag? Is it a featured Football story? It's hard to tell.

![image](https://user-images.githubusercontent.com/607807/45062492-28636700-b077-11e8-9f28-0b88ef5d8a29.png)

With the infinite scroll, some way to indicate pagination (especially in the URL) is necesary. Especially when someone clicks an article, then goes back but loses the position.

When articles load in infinite scroll, the amount of columns is inconsistent so the bottomost row keeps shifting around until more articles load.

# Article Page

This popup looks very out of place, perhaps it's a result of using a third party tool.

![image](https://user-images.githubusercontent.com/607807/45062586-8e4fee80-b077-11e8-8852-f1b30a544208.png)

The breadcrumbs are muted and easy to miss. (Not a bad thing, but could be displayed more prominently)

![image](https://user-images.githubusercontent.com/607807/45062723-49788780-b078-11e8-8cb9-d2879d5b1c06.png)

The area under the image, especially the caption, cause my eye to wander a lot. The caption should be aligned left for consistency.

![image](https://user-images.githubusercontent.com/607807/45062753-62813880-b078-11e8-89e7-9ff7e36ad622.png)

The area underneath the last paragraph feels very cluttered

![image](https://user-images.githubusercontent.com/607807/45062774-817fca80-b078-11e8-96d3-c81c47c9f647.png)

This particular sentence in the author bio can be better displayed as metadata, as there is a lot of redundancy:

![image](https://user-images.githubusercontent.com/607807/45062644-db33c500-b077-11e8-800c-187aac1959c3.png)

For example -

![image](https://user-images.githubusercontent.com/607807/45062702-277f0500-b078-11e8-9639-f506203c4e67.png)

The "More by Geoff" section could be better moved under the author bio, the positioning doesn't make sense, especially since most people don't pay attention to author names when they read a story.

![image](https://user-images.githubusercontent.com/607807/45062806-a7a56a80-b078-11e8-92a5-494381819b32.png)

The two `Login` links lead to two very different login pages, which I assume are very different login systems.

![image](https://user-images.githubusercontent.com/607807/45062616-ba6b6f80-b077-11e8-8c9c-c58c2a87017c.png)

The curation under the article page is inconsistent with the homepage, and confusing at best

![image](https://user-images.githubusercontent.com/607807/45062836-d1f72800-b078-11e8-8fac-87b9d8348ffa.png)

In fact, there is a very unorganized list of articles (with no clue on how they are sorted) with the share bar still present at the bottom when it should be gone.

![image](https://user-images.githubusercontent.com/607807/45062863-e6d3bb80-b078-11e8-98cb-e075849060a0.png)

# About Page

Not much extra stuff to point out with the about page, but the typography could also be improved here, and perhaps more actionable items (such as buttons or a contact form) could come in handy.

**Comment by davisshaver** [comment]
Great feedback, thanks @pixelyunicorn 💯 

I've triaged a bunch of them and made new issues for others. Going to close this issue for now but we'll have it as a reference later on.
